Role Name
=========

Wrapper to create and drop RCU schemas

Requirements
------------

This presumes the wlssoftware, wlsprep, and java roles have been run. At least an RCU executable is required and that is laid in with wlssoftware.


Role Variables
--------------

A list of component IDs to install.

    rcu_components:
      - STB

Passwords for both the SYS and schema users:

    rcu_sys_password: bad_sys_password
    rcu_schema_password: terrible_schema_password
    
Create the repository. Drop works too.

    rcu_action: createRepository
    
The prefix to create the schema as,

    rcu_prefix: DEV
    
Database connection info

    rcu_hostname: default.oracle.hostname
    rcu_port: 1521
    rcu_service: orcl
    
Place to put the temp install files, and where is the RCU executable

    rcu_temp_dir: /home/oracle/installer
    rcu_password_file: "{{ rcu_temp_dir }}/rcu_passwords.txt"
    rcu_executable: /home/oracle/middleware/oracle_common/bin/rcu

A simple way to hand in variables for complex RCU such as OSB or ODI:

    rcu_variables: "SOA_PROFILE_TYPE=SMALL,HEALTHCARE_INTEGRATION=NO"

Newer RCU installs such as WLS will sneak in an extra schema... because of course that's what these things need is more schema.

Set this to add N number of extra passwords so RCU will run successfully:

    rcu_fixup_count: 1

Dependencies
------------

No dependencies.

Example Playbook
----------------

Including an example of how to use the role, e.g., installing the schemas for EDQ.

[source, yaml]
----
    - hosts: admin
      become_user: oracle
      become: yes
      vars:
        rcu_components:
          - EDQ_CONF
          - EDQ_RES
          - EDQ_STAGING
          - STB
          - OPSS
          - IAU
          - IAU_APPEND
          - IAU_VIEWER
        rcu_action: createRepository
        rcu_temp_dir: /home/oracle/installer
        rcu_password_file: "{{ rcu_temp_dir }}/rcu_passwords.txt"
        rcu_executable: /home/oracle/middleware/oracle_common/bin/rcu
        rcu_variables: "SOA_PROFILE_TYPE=SMALL,HEALTHCARE_INTEGRATION=NO"
        
      roles:
         - staylorx.wls-rcu
----

Another example installing the schemas for OSB.

[source, yaml]
----
    - hosts: admin
      become_user: oracle
      become: yes
      vars:
        rcu_components:
          - STB
          - OPSS
          - SOAINFRA  
        rcu_action: createRepository
        rcu_temp_dir: /home/oracle/installer
        rcu_password_file: "{{ rcu_temp_dir }}/rcu_passwords.txt"
        rcu_executable: /home/oracle/middleware/oracle_common/bin/rcu
        rcu_variables: "SOA_PROFILE_TYPE=SMALL,HEALTHCARE_INTEGRATION=NO"
        
      roles:
         - staylorx.wls-rcu
----

License
-------

BSD, MIT

